import type { Provider } from './types'

export const STATIC_PROVIDERS: Provider[] = [
  // ─── POPULAR / MAJOR ───────────────────────────────────────────────────────

  {
    id: 'openai',
    name: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    authType: 'bearer',
    corsEnabled: true,
    category: 'popular',
    tags: ['popular'],
    fields: [
      { key: 'apiKey', label: 'API Key', placeholder: 'sk-...', secret: true },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic (Claude)',
    baseUrl: 'https://api.anthropic.com',
    authType: 'anthropic',
    corsEnabled: true,
    category: 'popular',
    tags: ['popular'],
    fields: [
      { key: 'apiKey', label: 'API Key', placeholder: 'sk-ant-...', secret: true },
    ],
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com',
    authType: 'gemini',
    corsEnabled: true,
    category: 'popular',
    tags: ['popular', 'google'],
    fields: [
      { key: 'apiKey', label: 'API Key', placeholder: 'AIza...', secret: true },
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    authType: 'bearer',
    corsEnabled: true,
    category: 'popular',
    tags: ['popular', 'fast'],
    fields: [
      { key: 'apiKey', label: 'API Key', placeholder: 'gsk_...', secret: true },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    baseUrl: 'https://api.mistral.ai/v1',
    authType: 'bearer',
    corsEnabled: true,
    category: 'popular',
    tags: ['popular', 'european'],
    fields: [
      { key: 'apiKey', label: 'API Key', secret: true },
    ],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    baseUrl: 'https://api.cohere.com/v1',
    authType: 'bearer',
    corsEnabled: true,
    category: 'popular',
    fields: [
      { key: 'apiKey', label: 'API Key', secret: true },
    ],
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    baseUrl: 'https://api.x.ai/v1',
    authType: 'bearer',
    corsEnabled: true,
    category: 'popular',
    tags: ['popular'],
    fields: [
      { key: 'apiKey', label: 'API Key', placeholder: 'xai-...', secret: true },
    ],
  },
  {
    id: 'perplexity',
    name: 'Perplexity AI',
    baseUrl: 'https://api.perplexity.ai',
    authType: 'bearer',
    corsEnabled: false,
    category: 'popular',
    tags: ['popular', 'search'],
    fields: [
      { key: 'apiKey', label: 'API Key', placeholder: 'pplx-...', secret: true },
    ],
  },

  // ─── CLOUD PROVIDERS (COMPLEX AUTH) ────────────────────────────────────────

  {
    id: 'bedrock',
    name: 'AWS Bedrock',
    authType: 'aws-sigv4',
    corsEnabled: true,
    category: 'cloud',
    tags: ['aws', 'cloud', 'enterprise'],
    fields: [
      { key: 'accessKeyId', label: 'Access Key ID', placeholder: 'AKIA...', secret: false },
      { key: 'secretAccessKey', label: 'Secret Access Key', secret: true },
      { key: 'region', label: 'AWS Region', placeholder: 'us-east-1', default: 'us-east-1' },
    ],
  },
  {
    id: 'azure',
    name: 'Azure OpenAI',
    authType: 'azure',
    corsEnabled: true,
    category: 'cloud',
    tags: ['azure', 'cloud', 'microsoft', 'enterprise'],
    fields: [
      { key: 'resourceName', label: 'Resource Name', placeholder: 'my-resource', hint: 'The name before .openai.azure.com' },
      { key: 'apiKey', label: 'API Key', secret: true },
    ],
  },

  // ─── OPENAI-COMPATIBLE ──────────────────────────────────────────────────────

  {
    id: 'together_ai',
    name: 'Together AI',
    baseUrl: 'https://api.together.xyz/v1',
    authType: 'bearer',
    corsEnabled: true,
    category: 'popular',
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'fireworks_ai',
    name: 'Fireworks AI',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    authType: 'bearer',
    corsEnabled: true,
    category: 'popular',
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    authType: 'bearer',
    corsEnabled: true,
    category: 'other',
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    baseUrl: 'https://api.cerebras.ai/v1',
    authType: 'bearer',
    corsEnabled: true,
    category: 'popular',
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'sambanova',
    name: 'SambaNova',
    baseUrl: 'https://api.sambanova.ai/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'other',
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'nebius',
    name: 'Nebius AI Studio',
    baseUrl: 'https://api.studio.nebius.ai/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'other',
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    authType: 'bearer',
    corsEnabled: true,
    category: 'popular',
    tags: ['popular', 'aggregator'],
    fields: [{ key: 'apiKey', label: 'API Key', placeholder: 'sk-or-...', secret: true }],
  },
  {
    id: 'nvidia_nim',
    name: 'NVIDIA NIM',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'other',
    fields: [{ key: 'apiKey', label: 'API Key', placeholder: 'nvapi-...', secret: true }],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'chinese',
    tags: ['chinese', 'popular'],
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'huggingface',
    name: 'HuggingFace',
    baseUrl: 'https://router.huggingface.co/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'popular',
    fields: [{ key: 'apiKey', label: 'Access Token', placeholder: 'hf_...', secret: true }],
  },
  {
    id: 'ai21',
    name: 'AI21 Labs',
    baseUrl: 'https://api.ai21.com/studio/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'other',
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'novita',
    name: 'Novita AI',
    baseUrl: 'https://api.novita.ai/v3/openai',
    authType: 'bearer',
    corsEnabled: false,
    category: 'other',
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'hyperbolic',
    name: 'Hyperbolic',
    baseUrl: 'https://api.hyperbolic.xyz/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'other',
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'lambda_ai',
    name: 'Lambda AI',
    baseUrl: 'https://api.lambda.ai/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'other',
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'featherless_ai',
    name: 'Featherless AI',
    baseUrl: 'https://api.featherless.ai/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'other',
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'meta_llama',
    name: 'Meta Llama API',
    baseUrl: 'https://api.llama.com/compat/v1/',
    authType: 'bearer',
    corsEnabled: false,
    category: 'other',
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'codestral',
    name: 'Codestral (Mistral)',
    baseUrl: 'https://codestral.mistral.ai/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'other',
    tags: ['mistral', 'code'],
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },

  // ─── CHINESE PROVIDERS ──────────────────────────────────────────────────────

  {
    id: 'moonshot',
    name: 'Moonshot AI (Kimi)',
    baseUrl: 'https://api.moonshot.cn/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'chinese',
    tags: ['chinese'],
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'dashscope',
    name: 'Qwen / DashScope (Alibaba)',
    baseUrl: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'chinese',
    tags: ['chinese', 'alibaba'],
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'volcengine',
    name: 'ByteDance (Doubao/Ark)',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    authType: 'bearer',
    corsEnabled: false,
    category: 'chinese',
    tags: ['chinese', 'bytedance'],
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    baseUrl: 'https://api.minimax.io/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'chinese',
    tags: ['chinese'],
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'zai',
    name: 'Zhipu AI (GLM)',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    authType: 'zhipu',
    corsEnabled: false,
    category: 'chinese',
    tags: ['chinese'],
    fields: [
      { key: 'apiKey', label: 'API Key', placeholder: 'id.secret', secret: true, hint: 'Format: {id}.{secret}' },
    ],
  },
  {
    id: 'stepfun',
    name: 'StepFun (阶跃星辰)',
    baseUrl: 'https://api.stepfun.com/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'chinese',
    tags: ['chinese'],
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'baichuan',
    name: 'Baichuan AI (百川)',
    baseUrl: 'https://api.baichuan-ai.com/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'chinese',
    tags: ['chinese'],
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },
  {
    id: 'tencent',
    name: 'Tencent Hunyuan (混元)',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    authType: 'bearer',
    corsEnabled: false,
    category: 'chinese',
    tags: ['chinese', 'tencent'],
    fields: [{ key: 'apiKey', label: 'API Key', secret: true }],
  },

  // ─── LOCAL PROVIDERS ────────────────────────────────────────────────────────

  {
    id: 'ollama',
    name: 'Ollama (Local)',
    authType: 'bearer',
    corsEnabled: false,
    category: 'local',
    isLocal: true,
    tags: ['local', 'free'],
    fields: [
      { key: 'baseUrl', label: 'Base URL', placeholder: 'http://localhost:11434/v1', default: 'http://localhost:11434/v1' },
      { key: 'apiKey', label: 'API Key (optional)', default: 'ollama', secret: false, required: false },
    ],
  },
  {
    id: 'lmstudio',
    name: 'LM Studio (Local)',
    authType: 'bearer',
    corsEnabled: false,
    category: 'local',
    isLocal: true,
    tags: ['local', 'free'],
    fields: [
      { key: 'baseUrl', label: 'Base URL', placeholder: 'http://localhost:1234/v1', default: 'http://localhost:1234/v1' },
      { key: 'apiKey', label: 'API Key (optional)', default: 'lm-studio', secret: false, required: false },
    ],
  },
  {
    id: 'vllm',
    name: 'vLLM (Self-hosted)',
    authType: 'bearer',
    corsEnabled: false,
    category: 'local',
    isLocal: true,
    tags: ['local', 'self-hosted'],
    fields: [
      { key: 'baseUrl', label: 'Base URL', placeholder: 'http://localhost:8000/v1' },
      { key: 'apiKey', label: 'API Key', secret: true },
    ],
  },
]

// Map for O(1) lookup
export const STATIC_PROVIDER_MAP = new Map(
  STATIC_PROVIDERS.map((p) => [p.id, p])
)
